const express = require('express');
const cors = require('cors');
const helmet = require('helmet');
const PDFDocument = require('pdfkit');
const nodemailer = require('nodemailer');

const app = express();
const PORT = process.env.PORT || 3003;

app.use(helmet());
app.use(cors());
app.use(express.json());

// Generate PDF report
app.post('/generate', (req, res) => {
  try {
    const { patientInfo, symptoms, diagnoses, timestamp } = req.body;
    
    const doc = new PDFDocument();
    let buffers = [];
    
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', () => {
      const pdfData = Buffer.concat(buffers);
      res.setHeader('Content-Type', 'application/pdf');
      res.setHeader('Content-Disposition', 'attachment; filename=diagnostic-report.pdf');
      res.send(pdfData);
    });

    // PDF Content
    doc.fontSize(20).text('Clinical Diagnostic Report', 100, 100);
    doc.moveDown();
    
    doc.fontSize(14).text(`Generated: ${new Date(timestamp).toLocaleString()}`, 100);
    doc.moveDown();
    
    if (patientInfo) {
      doc.fontSize(16).text('Patient Information:', 100);
      doc.fontSize(12).text(`Name: ${patientInfo.name || 'N/A'}`, 120);
      doc.text(`Age: ${patientInfo.age || 'N/A'}`, 120);
      doc.text(`Gender: ${patientInfo.gender || 'N/A'}`, 120);
      doc.moveDown();
    }
    
    doc.fontSize(16).text('Reported Symptoms:', 100);
    symptoms.forEach((symptom, index) => {
      doc.fontSize(12).text(`${index + 1}. ${symptom}`, 120);
    });
    doc.moveDown();
    
    doc.fontSize(16).text('Diagnostic Results:', 100);
    diagnoses.forEach((diagnosis, index) => {
      doc.fontSize(14).text(`${index + 1}. ${diagnosis.diagnosis}`, 120);
      doc.fontSize(12).text(`   Confidence: ${diagnosis.confidence}%`, 120);
      doc.text(`   Reasoning: ${diagnosis.reasoning}`, 120);
      if (diagnosis.recommendations && diagnosis.recommendations.length > 0) {
        doc.text('   Recommendations:', 120);
        diagnosis.recommendations.forEach(rec => {
          doc.text(`   • ${rec}`, 140);
        });
      }
      doc.moveDown(0.5);
    });
    
    doc.moveDown();
    doc.fontSize(10).text('This report is generated by Clinical Diagnostic Assistant and should be reviewed by a qualified healthcare professional.', 100);
    
    doc.end();
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ error: 'Failed to generate report' });
  }
});

// Send report via email
app.post('/email', async (req, res) => {
  try {
    const { email, reportData, subject = 'Diagnostic Report' } = req.body;
    
    if (!email || !reportData) {
      return res.status(400).json({ error: 'Email and report data required' });
    }

    // Create PDF buffer
    const doc = new PDFDocument();
    let buffers = [];
    
    doc.on('data', buffers.push.bind(buffers));
    doc.on('end', async () => {
      const pdfBuffer = Buffer.concat(buffers);
      
      // Configure email transporter (using Gmail as example)
      const transporter = nodemailer.createTransporter({
        service: 'gmail',
        auth: {
          user: process.env.EMAIL_USER || 'your-email@gmail.com',
          pass: process.env.EMAIL_PASS || 'your-app-password'
        }
      });

      const mailOptions = {
        from: process.env.EMAIL_USER || 'noreply@clinicaldiagnostic.com',
        to: email,
        subject: subject,
        text: 'Please find your diagnostic report attached.',
        html: `
          <h2>Clinical Diagnostic Report</h2>
          <p>Dear Patient,</p>
          <p>Please find your diagnostic report attached to this email.</p>
          <p><strong>Important:</strong> This report should be reviewed with a qualified healthcare professional.</p>
          <p>Best regards,<br>Clinical Diagnostic Assistant Team</p>
        `,
        attachments: [
          {
            filename: 'diagnostic-report.pdf',
            content: pdfBuffer,
            contentType: 'application/pdf'
          }
        ]
      };

      try {
        await transporter.sendMail(mailOptions);
        res.json({ success: true, message: 'Report sent successfully' });
      } catch (emailError) {
        console.error('Email sending error:', emailError);
        res.status(500).json({ error: 'Failed to send email' });
      }
    });

    // Generate PDF content (same as above)
    const { patientInfo, symptoms, diagnoses, timestamp } = reportData;
    
    doc.fontSize(20).text('Clinical Diagnostic Report', 100, 100);
    doc.moveDown();
    
    doc.fontSize(14).text(`Generated: ${new Date(timestamp).toLocaleString()}`, 100);
    doc.moveDown();
    
    if (patientInfo) {
      doc.fontSize(16).text('Patient Information:', 100);
      doc.fontSize(12).text(`Name: ${patientInfo.name || 'N/A'}`, 120);
      doc.text(`Age: ${patientInfo.age || 'N/A'}`, 120);
      doc.text(`Gender: ${patientInfo.gender || 'N/A'}`, 120);
      doc.moveDown();
    }
    
    doc.fontSize(16).text('Reported Symptoms:', 100);
    symptoms.forEach((symptom, index) => {
      doc.fontSize(12).text(`${index + 1}. ${symptom}`, 120);
    });
    doc.moveDown();
    
    doc.fontSize(16).text('Diagnostic Results:', 100);
    diagnoses.forEach((diagnosis, index) => {
      doc.fontSize(14).text(`${index + 1}. ${diagnosis.diagnosis}`, 120);
      doc.fontSize(12).text(`   Confidence: ${diagnosis.confidence}%`, 120);
      doc.text(`   Reasoning: ${diagnosis.reasoning}`, 120);
      if (diagnosis.recommendations && diagnosis.recommendations.length > 0) {
        doc.text('   Recommendations:', 120);
        diagnosis.recommendations.forEach(rec => {
          doc.text(`   • ${rec}`, 140);
        });
      }
      doc.moveDown(0.5);
    });
    
    doc.end();
  } catch (error) {
    console.error('Email report error:', error);
    res.status(500).json({ error: 'Failed to send report' });
  }
});

app.get('/health', (req, res) => {
  res.json({ status: 'OK', service: 'reporting' });
});

app.listen(PORT, () => {
  console.log(`Reporting Service running on port ${PORT}`);
});